allowBuilds:
  '@firebase/util': true
  esbuild: true
  protobufjs: true
  re2: true
  workerd: true
minimumReleaseAgeExclude:
  - '@cloudflare/workerd-darwin-64@1.20260927.1'
  - '@cloudflare/workerd-darwin-arm64@1.20260927.1'
  - '@cloudflare/workerd-linux-64@1.20260927.1'
  - '@cloudflare/workerd-linux-arm64@1.20260927.1'
  - '@cloudflare/workerd-windows-64@1.20260927.1'
  - workerd@1.20260927.1
